Repository RunOnFlux/flux, pull requests merged in 2024-07, with the labels that each got.

#1322 Feature: Add OCI Image support and refactor image testing
  .eslintrc.js
  ZelBack/src/services/appsService.js
  ZelBack/src/services/dockerService.js
  ZelBack/src/services/generalService.js
  ZelBack/src/services/serviceHelper.js
  ZelBack/src/services/utils/imageVerifier.js
  apiServer.js
  helpers/repositories.json
  package.json
  tests/ZelBack/appsService.js
  tests/unit/appsService.test.js
  tests/unit/data/registryResponses.js
  tests/unit/generalService.test.js
  tests/unit/imageVerifier.test.js
Labels: ready to merge

#1344 Feature: rework websockets
  ZelBack/src/lib/fluxServer.js
  ZelBack/src/lib/server.js
  ZelBack/src/lib/socketHandlers.js
  ZelBack/src/lib/socketIoServer.js
  ZelBack/src/lib/socketServer.js
  ZelBack/src/routes.js
  ZelBack/src/services/fluxCommunication.js
  ZelBack/src/services/fluxNetworkHelper.js
  ZelBack/src/services/idService.js
  apiServer.js
  package.json
  tests/ZelBack/apiTests.js
  tests/unit/fluxCommunication.test.js
  tests/unit/fluxNetworkHelper.test.js
  tests/unit/fluxServer.test.js
  tests/unit/socketIoServer.test.js
  tests/unit/socketServer.test.js
Labels: ready to merge

#1368 Email SSO login fix
  HomeUI/src/libs/firebase.js
  HomeUI/src/views/Home.vue
Labels: v5.17.0

#1363 Feature - enable fluxd subscription endpoint
  ZelBack/config/default.js
  ZelBack/src/services/daemonService/daemonServiceTransactionRpcs.js
  ZelBack/src/services/daemonService/daemonServiceUtils.js
  ZelBack/src/services/fluxService.js
  ZelBack/src/services/serviceManager.js
  ZelBack/src/services/systemService.js
  ZelBack/src/services/utils/daemonConfig.js
  ZelBack/src/services/utils/daemonrpcClient.js
  lib/fullnode/README
  lib/fullnode/index.js
  lib/fullnode/package.json
  package.json
  tests/unit/daemonConfig.test.js
  tests/unit/daemonServiceTransactionRpcs.test.js
  tests/unit/daemonServiceUtils.test.js
  tests/unit/data/fluxdConfigs.js
  tests/unit/systemService.test.js
Labels: ready to merge, testing required
